# Dockerfile for Kurnia files (KWG, KLV)
# See github.com/andy-k/wolges
FROM rust:1.68.0
ADD . /workdir
WORKDIR /workdir
RUN ["cargo", "build", "--release", "--bin", "buildlex"]
ENTRYPOINT ["cargo", "run", "--release", "--bin", "buildlex"]