package cross_set

import (
	"github.com/domino14/macondo/board"
	"github.com/domino14/macondo/gaddag"
	"github.com/domino14/macondo/move"
	"github.com/domino14/macondo/tinymove"
	"github.com/domino14/word-golib/tilemapping"
)

type CrossSet = board.CrossSet
type Board = board.GameBoard

const (
	Left       = board.LeftDirection
	Right      = board.RightDirection
	Horizontal = board.HorizontalDirection
	Vertical   = board.VerticalDirection
)

type GenericMove interface {
	PlayLength() int
}

// Public cross_set.Generator Interface
// There are two concrete implementations below,
// - CrossScoreOnlyGenerator{Dist}
// - GaddagCrossSetGenerator{Dist, Gaddag}

type Generator interface {
	Generate(b *Board, row int, col int, dir board.BoardDirection)
	GenerateAll(b *Board)
	UpdateForMove(b *Board, m *move.Move)
	UpdateForSmallMove(b *Board, m *tinymove.SmallMove, moveTiles *[board.MaxBoardDim]tilemapping.MachineLetter)
}

// generateAll generates all cross-sets. It goes through the entire
// board; our anchor algorithm doesn't quite match the one in the Gordon
// paper.
// We do this for both transpositions of the board.
func generateAll(g Generator, b *Board) {
	n := b.Dim()
	for i := 0; i < n; i++ {
		for j := 0; j < n; j++ {
			g.Generate(b, i, j, Horizontal)
		}
	}
	b.Transpose()
	for i := 0; i < n; i++ {
		for j := 0; j < n; j++ {
			g.Generate(b, i, j, Vertical)
		}
	}
	// And transpose back to the original orientation.
	b.Transpose()
}

// Assumes all across words are HORIZONTAL.
func calcForAcross(rowStart int, colStart int, csd board.BoardDirection,
	g Generator, m *move.Move, b *Board) {

	// log.Debug().Msgf("Updating for move: %s", m.ShortDescription())
	for row := rowStart; row < m.PlayLength()+rowStart; row++ {
		if m.Tiles()[row-rowStart] == 0 {
			// No new "across word" was generated by this tile, so no need
			// to update cross set.
			continue
		}
		// Otherwise, look along this row. Note, the edge is still part
		// of the word.
		rightCol := b.WordEdge(int(row), int(colStart), Right)
		leftCol := b.WordEdge(int(row), int(colStart), Left)
		g.Generate(b, int(row), int(rightCol)+1, csd)
		g.Generate(b, int(row), int(leftCol)-1, csd)
		// This should clear the cross set on the just played tile.
		g.Generate(b, int(row), int(colStart), csd)
	}
}

func calcForAcrossSmall(rowStart int, colStart int, csd board.BoardDirection,
	g Generator, m *tinymove.SmallMove, b *Board, moveTiles *[board.MaxBoardDim]tilemapping.MachineLetter) {

	// log.Debug().Msgf("Updating for move: %s", m.ShortDescription())
	for row := rowStart; row < m.PlayLength()+rowStart; row++ {
		if moveTiles[row-rowStart] == 0 {
			// No new "across word" was generated by this tile, so no need
			// to update cross set.
			continue
		}
		// Otherwise, look along this row. Note, the edge is still part
		// of the word.
		rightCol := b.WordEdge(int(row), int(colStart), Right)
		leftCol := b.WordEdge(int(row), int(colStart), Left)
		g.Generate(b, int(row), int(rightCol)+1, csd)
		g.Generate(b, int(row), int(leftCol)-1, csd)
		// This should clear the cross set on the just played tile.
		g.Generate(b, int(row), int(colStart), csd)
	}
}

// assumes self is HORIZONTAL
func calcForSelf(rowStart int, colStart int, csd board.BoardDirection,
	g Generator, m GenericMove, b *Board) {
	// Generate cross-sets on either side of the word.
	for col := int(colStart) - 1; col <= int(colStart)+m.PlayLength(); col++ {
		g.Generate(b, int(rowStart), col, csd)
	}
}

func updateForMove(g Generator, b *Board, m *move.Move) {

	// log.Trace().Msgf("Updating for move: %s", m.ShortDescription())
	row, col, vertical := m.CoordsAndVertical()
	// Every tile placed by this new move creates new "across" words, and we need
	// to update the cross sets on both sides of these across words, as well
	// as the cross sets for THIS word.

	if vertical {
		calcForAcross(row, col, Horizontal, g, m, b)
		b.Transpose()
		row, col = col, row
		calcForSelf(row, col, Vertical, g, m, b)
		b.Transpose()
	} else {
		calcForSelf(row, col, Horizontal, g, m, b)
		b.Transpose()
		row, col = col, row
		calcForAcross(row, col, Vertical, g, m, b)
		b.Transpose()
	}
}

func updateForSmallMove(g Generator, b *Board, m *tinymove.SmallMove, moveTiles *[board.MaxBoardDim]tilemapping.MachineLetter) {
	row, col, vertical := m.CoordsAndVertical()
	// Every tile placed by this new move creates new "across" words, and we need
	// to update the cross sets on both sides of these across words, as well
	// as the cross sets for THIS word.

	if vertical {
		calcForAcrossSmall(row, col, Horizontal, g, m, b, moveTiles)
		b.Transpose()
		row, col = col, row
		calcForSelf(row, col, Vertical, g, m, b)
		b.Transpose()
	} else {
		calcForSelf(row, col, Horizontal, g, m, b)
		b.Transpose()
		row, col = col, row
		calcForAcrossSmall(row, col, Vertical, g, m, b, moveTiles)
		b.Transpose()
	}
}

// ----------------------------------------------------------------------
// Use a CrossScoreOnlyGenerator when you don't need cross sets

type CrossScoreOnlyGenerator struct {
	Dist *tilemapping.LetterDistribution
}

func (g *CrossScoreOnlyGenerator) Generate(b *Board, row int, col int, dir board.BoardDirection) {
	genCrossScore(b, row, col, dir, g.Dist)
}

func (g *CrossScoreOnlyGenerator) GenerateAll(b *Board) {
	generateAll(g, b)
}

func (g *CrossScoreOnlyGenerator) UpdateForMove(b *Board, m *move.Move) {
	updateForMove(g, b, m)
}

func (g *CrossScoreOnlyGenerator) UpdateForSmallMove(b *Board, m *tinymove.SmallMove, n *[board.MaxBoardDim]tilemapping.MachineLetter) {
	panic("UpdateForSmallMove should never be called with CrossScoreOnlyGenerator")
}

// Wrapper functions to save rewriting all the tests

func GenAllCrossScores(b *Board, ld *tilemapping.LetterDistribution) {
	gen := CrossScoreOnlyGenerator{Dist: ld}
	gen.GenerateAll(b)
}

// ----------------------------------------------------------------------
// Implementation for CrossScoreOnlyGenerator

func genCrossScore(b *Board, row int, col int, dir board.BoardDirection,
	ld *tilemapping.LetterDistribution) {
	if row < 0 || row >= b.Dim() || col < 0 || col >= b.Dim() {
		return
	}
	// If the square has a letter in it, its cross set and cross score
	// should both be 0
	if b.HasLetter(row, col) {
		b.SetCrossScore(row, col, 0, dir)
		return
	}
	// If there's no tile adjacent to this square in any direction,
	// every letter is allowed.
	if b.LeftAndRightEmpty(row, col) {
		b.SetCrossScore(row, col, 0, dir)
		return
	}
	// If we are here, there is a letter to the left, to the right, or both.
	// start from the right and go backwards.
	rightCol := b.WordEdge(row, col+1, Right)
	if rightCol == col {
		score := b.TraverseBackwardsForScore(row, col-1, ld)
		b.SetCrossScore(row, col, score, dir)
	} else {
		// Otherwise, the right is not empty. Check if the left is empty,
		// if so we just traverse right, otherwise, we try every letter.
		scoreR := b.TraverseBackwardsForScore(row, rightCol, ld)
		scoreL := b.TraverseBackwardsForScore(row, col-1, ld)
		b.SetCrossScore(row, col, scoreR+scoreL, dir)
	}
}

// ----------------------------------------------------------------------
// GaddagCrossSetGenerator generates cross sets via a gaddag

type GaddagCrossSetGenerator struct {
	Dist   *tilemapping.LetterDistribution
	Gaddag gaddag.WordGraph
}

func (g *GaddagCrossSetGenerator) Generate(b *Board, row int, col int, dir board.BoardDirection) {
	GenCrossSet(b, row, col, dir, g.Gaddag, g.Dist)
}

func (g *GaddagCrossSetGenerator) GenerateAll(b *Board) {
	generateAll(g, b)
}

func (g *GaddagCrossSetGenerator) UpdateForMove(b *Board, m *move.Move) {
	updateForMove(g, b, m)
}

func (g *GaddagCrossSetGenerator) UpdateForSmallMove(b *Board, m *tinymove.SmallMove, moveTiles *[board.MaxBoardDim]tilemapping.MachineLetter) {
	updateForSmallMove(g, b, m, moveTiles)
}

// Wrapper functions to save rewriting all the tests

func GenAllCrossSets(b *Board, gd gaddag.WordGraph, ld *tilemapping.LetterDistribution) {
	gen := GaddagCrossSetGenerator{Dist: ld, Gaddag: gd}
	gen.GenerateAll(b)
}

func UpdateCrossSetsForMove(b *Board, m *move.Move,
	gd gaddag.WordGraph, ld *tilemapping.LetterDistribution) {
	gen := GaddagCrossSetGenerator{Dist: ld, Gaddag: gd}
	gen.UpdateForMove(b, m)
}

// ----------------------------------------------------------------------
// Implementation for GaddagCrossSetGenerator

func traverseBackwards(b *Board, row int, col int,
	nodeIdx uint32, checkLetterSet bool, leftMostCol int,
	gaddag gaddag.WordGraph) (uint32, bool) {
	// Traverse the letters on the board backwards (left). Return the index
	// of the node in the gaddag for the left-most letter, and a boolean
	// indicating if the gaddag path was valid.
	// If checkLetterSet is true, then we traverse until leftMostCol+1 and
	// check the letter set of this node to see if it includes the letter
	// at leftMostCol
	for b.PosExists(row, col) {
		ml := b.GetLetter(row, col)
		if ml == 0 {
			break
		}

		if checkLetterSet && col == leftMostCol {
			if gaddag.InLetterSet(ml, nodeIdx) {
				return nodeIdx, true
			}
			// Give up early; if we're checking letter sets we only care about
			// this column.
			return nodeIdx, false
		}

		nodeIdx = gaddag.NextNodeIdx(nodeIdx, ml.Unblank())
		if nodeIdx == 0 {
			// There is no path in the gaddag for this word part; this
			// can occur if a phony was played and stayed on the board
			// and the phony has no extensions for example, or if it's
			// a real word with no further extensions.
			return nodeIdx, false
		}

		col--
	}

	return nodeIdx, true
}

// getLetterSets computes the letter set (tiles that accept) and extension set
// (tiles that have arcs) at a given KWG node index, mirroring magpie's
// kwg_get_letter_sets. Both exclude the separation token (tile 0).
func getLetterSets(gd gaddag.WordGraph, nodeIdx uint32) (letterSet uint64, extensionSet uint64) {
	if nodeIdx == 0 {
		return 0, 0
	}
	for i := nodeIdx; ; i++ {
		t := gd.Tile(i)
		if t != 0 {
			bit := uint64(1) << t
			extensionSet |= bit
			if gd.Accepts(i) {
				letterSet |= bit
			}
		}
		if gd.IsEnd(i) {
			break
		}
	}
	return
}

// extSetWithBlank adds the blank bit (bit 0) to an extension set if the set
// is non-empty, since a blank can designate any letter.
func extSetWithBlank(es uint64) uint64 {
	if es != 0 {
		return es | 1
	}
	return 0
}

// throughDir returns the direction perpendicular to dir.
// When computing cross-sets for direction dir, the extension sets are stored
// in the perpendicular ("through") direction, because that's the direction
// the move generator actually traverses when placing tiles.
func throughDir(dir board.BoardDirection) board.BoardDirection {
	if dir == Horizontal {
		return Vertical
	}
	return Horizontal
}

// GenCrossSet generates a cross-set and extension sets for each individual square.
func GenCrossSet(b *Board, row int, col int, dir board.BoardDirection,
	gd gaddag.WordGraph, ld *tilemapping.LetterDistribution) {

	if row < 0 || row >= b.Dim() || col < 0 || col >= b.Dim() {
		return
	}
	tDir := throughDir(dir)

	// If the square has a letter in it, its cross set and cross score
	// should both be 0. Extension sets for filled squares will be set
	// during cross-set generation of adjacent empty squares.
	if b.HasLetter(row, col) {
		b.ClearCrossSet(row, col, dir)
		b.SetCrossScore(row, col, 0, dir)
		// Don't reset ext sets here - they'll be set by adjacent empty squares.
		return
	}
	// If there's no tile adjacent to this square in any direction,
	// every letter is allowed, and extension sets are trivial.
	if b.LeftAndRightEmpty(row, col) {
		b.SetCrossSet(row, col, board.TrivialCrossSet, dir)
		b.SetCrossScore(row, col, 0, dir)
		b.SetLeftExtSet(row, col, tDir, board.TrivialCrossSet)
		b.SetRightExtSet(row, col, tDir, board.TrivialCrossSet)
		return
	}
	// If we are here, there is a letter to the left, to the right, or both.
	rightCol := b.WordEdge(row, col+1, Right)
	leftCol := b.WordEdge(row, col-1, Left)

	nonemptyToLeft := leftCol < col
	nonemptyToRight := rightCol > col

	var scoreL, scoreR int
	var lNodeIdx, rNodeIdx uint32
	var lPathValid, rPathValid bool
	var leftsideLeftxSet, leftsideRightxSet uint64
	var rightsideLeftxSet, rightsideRightxSet uint64

	if nonemptyToLeft {
		lNodeIdx, lPathValid = traverseBackwards(b, row, col-1,
			gd.GetRootNodeIndex(), false, 0, gd)
		scoreL = b.TraverseBackwardsForScore(row, col-1, ld)
		if lPathValid {
			_, leftsideLeftxSet = getLetterSets(gd, lNodeIdx)
			sIdx := gd.NextNodeIdx(lNodeIdx, 0)
			if sIdx != 0 {
				_, leftsideRightxSet = getLetterSets(gd, sIdx)
			}
		}
		// Store extension sets on the rightmost tile of the left-side word
		// (col-1 is the square immediately left of the empty square).
		b.SetLeftExtSet(row, col-1, tDir, extSetWithBlank(leftsideLeftxSet))
		b.SetRightExtSet(row, col-1, tDir, extSetWithBlank(leftsideRightxSet))
		// Also store leftx on the square left of the entire left-side word,
		// so shadow can determine if extending further left is possible.
		if leftCol > 0 {
			b.SetLeftExtSet(row, leftCol-1, tDir, extSetWithBlank(leftsideLeftxSet))
		}
	}

	if nonemptyToRight {
		rNodeIdx, rPathValid = traverseBackwards(b, row, rightCol,
			gd.GetRootNodeIndex(), false, 0, gd)
		scoreR = b.TraverseBackwardsForScore(row, rightCol, ld)
		if rPathValid {
			_, rightsideLeftxSet = getLetterSets(gd, rNodeIdx)
			sIdx := gd.NextNodeIdx(rNodeIdx, 0)
			if sIdx != 0 {
				_, rightsideRightxSet = getLetterSets(gd, sIdx)
			}
		}
		// Store extension sets on the leftmost tile of the right-side word.
		b.SetLeftExtSet(row, rightCol, tDir, extSetWithBlank(rightsideLeftxSet))
		b.SetRightExtSet(row, rightCol, tDir, extSetWithBlank(rightsideRightxSet))
		// Store leftx on the empty square itself for right-side tiles.
		b.SetLeftExtSet(row, col, tDir, extSetWithBlank(rightsideLeftxSet))
	}

	// Now compute the cross-set itself.
	b.SetCrossScore(row, col, scoreL+scoreR, dir)

	if nonemptyToLeft && nonemptyToRight {
		// Both sides have tiles. Try each tile from the right side and check
		// if it leads back through the left side.
		if !lPathValid || !rPathValid {
			b.SetCrossSet(row, col, 0, dir)
			return
		}
		b.SetCrossSet(row, col, 0, dir)
		for i := rNodeIdx; ; i++ {
			t := gd.Tile(i)
			if t != 0 {
				// Only try letters possible in right extensions from left side.
				if leftsideRightxSet&(uint64(1)<<t) != 0 {
					nn := gd.ArcIndex(i)
					_, success := traverseBackwards(b, row, col-1, nn, true, leftCol, gd)
					if success {
						b.SetCrossSetLetter(row, col, dir, tilemapping.MachineLetter(t))
					}
				}
			}
			if gd.IsEnd(i) {
				break
			}
		}
	} else if nonemptyToLeft {
		if !lPathValid {
			b.SetCrossSet(row, col, 0, dir)
			return
		}
		sIdx := gd.NextNodeIdx(lNodeIdx, 0)
		letterSet := gd.GetLetterSet(sIdx)
		b.SetCrossSet(row, col, CrossSet(letterSet), dir)
	} else if nonemptyToRight {
		if !rPathValid {
			b.SetCrossSet(row, col, 0, dir)
			return
		}
		letterSet := gd.GetLetterSet(rNodeIdx)
		b.SetCrossSet(row, col, CrossSet(letterSet), dir)
	}
}
