// wmp_equivalence_test.go: verifies that the WMP-on and WMP-off paths
// produce equivalent move-generation results across racks, board states,
// and play recorders. If the WMP integration is functionally correct,
// both paths must agree on the top play AND on the full Top-N list.
package montecarlo

import (
	"testing"

	"github.com/domino14/word-golib/kwg"
	"github.com/domino14/word-golib/tilemapping"
	"github.com/matryer/is"

	"github.com/domino14/macondo/cgp"
	"github.com/domino14/macondo/equity"
	"github.com/domino14/macondo/move"
	"github.com/domino14/macondo/movegen"
	wmppkg "github.com/domino14/macondo/wmp"
)

// TestWMPEquivalentTopPlay runs the GenAllWithShadow + TopPlayOnlyRecorder
// pipeline once with WMP off and once with WMP on across several racks
// and board positions, and asserts the top play is identical (same word,
// same coords, same score, same equity to within 1e-6).
//
// Coverage:
//   - Blankless racks, single-blank racks, double-blank racks
//   - Mid-game CGP, empty board, near-endgame (1 in bag), exchange position
//   - Bingo-only racks, exchange-best racks
func TestWMPEquivalentTopPlay(t *testing.T) {
	is := is.New(t)
	_, wmpPath := requireWMPSetup(t)

	w, err := wmppkg.LoadFromFile("CSW24", wmpPath)
	is.NoErr(err)

	for _, c := range equivalenceCases {
		c := c
		t.Run(c.name, func(t *testing.T) {
			runTopPlayEquivalence(t, w, c)
		})
	}
}

// TestWMPTopNAreLegalPlays runs the WMP-on path through the
// TopNPlayRecorder (N=10) and asserts that every play it returns also
// appears in the *full* no-WMP play list (generated by AllPlaysRecorder)
// with identical score and equity. This is the cleanest correctness
// invariant we can express:
//
//   - Catches WMP scoring bugs (score or equity off for an otherwise
//     valid play).
//   - Catches WMP fabricating plays that aren't legal at all.
//   - Catches WMP generating plays at the wrong board coords.
//
// We deliberately do NOT assert the reverse direction (every noWMP
// play that ranks high enough must be in the WMP Top-N). The WMP
// path uses tighter shadow upper bounds via
// NonplaythroughBestLeaveValues, which can legitimately prune anchors
// that would contribute lower-ranked plays. For Top-1 — which is what
// sims consume — TestWMPEquivalentTopPlay already asserts exact
// equality.
func TestWMPTopNAreLegalPlays(t *testing.T) {
	is := is.New(t)
	_, wmpPath := requireWMPSetup(t)

	w, err := wmppkg.LoadFromFile("CSW24", wmpPath)
	is.NoErr(err)

	for _, c := range equivalenceCases {
		c := c
		t.Run(c.name, func(t *testing.T) {
			runTopNAreLegal(t, w, c, 10)
		})
	}
}

// equivalenceCase is a (description, CGP, rack) triple. The CGP must
// be a CSW24 position; the rack overrides whatever rack is in the CGP.
type equivalenceCase struct {
	name string
	cgp  string
	rack string
}

var equivalenceCases = []equivalenceCase{
	// Mid-game position from the existing benchmark CGP. The rack is
	// dominated by ZIET / similar; helped catch the original
	// integration bugs.
	{name: "midgame_EEEIILZ", cgp: benchSimCGP, rack: "EEEIILZ"},
	{name: "midgame_AEINRST_bingo", cgp: benchSimCGP, rack: "AEINRST"},
	{name: "midgame_AEILORS_bingo", cgp: benchSimCGP, rack: "AEILORS"},
	{name: "midgame_DGIQTUV", cgp: benchSimCGP, rack: "DGIQTUV"},
	{name: "midgame_BFHKMOR", cgp: benchSimCGP, rack: "BFHKMOR"},

	// Single-blank racks. Exercises writeBlankWords / wmpBlankPossibilities
	// and the per-blank attribution recursion in recordWMPPlaysForWord.
	{name: "midgame_blank_EINRST", cgp: benchSimCGP, rack: "?EINRST"},
	{name: "midgame_blank_AEELRST", cgp: benchSimCGP, rack: "?ELORST"},

	// Double-blank rack. Exercises writeDoubleBlankWords and the
	// nested per-blank recursion (one of the trickiest paths).
	{name: "midgame_double_blank_EINRS", cgp: benchSimCGP, rack: "??EINRS"},

	// Empty board with a bingo rack. Exercises the placementAdjustment
	// branch and the empty-board anchor handling.
	{name: "empty_board_AEINRST", cgp: emptyBoardCGP, rack: "AEINRST"},
	{name: "empty_board_blank_EINRST", cgp: emptyBoardCGP, rack: "?EINRST"},

	// Near pre-endgame: heavy playthrough position from a real CSW24
	// game. Exercises the late-bag wmpLeaves branch and equity bounds.
	{name: "late_bag_AFLOORY", cgp: explainerEndCGP, rack: "AFLOORY"},
	{name: "late_bag_blank_FLOORY", cgp: explainerEndCGP, rack: "?FLOORY"},

	// Exchange-best rack on a non-empty board. The exchange path itself
	// doesn't go through WMP, but the surrounding GenAllWithShadow flow
	// must still produce the same top play (which here is an exchange).
	{name: "exchange_best_IIIUUVV", cgp: benchSimCGP, rack: "IIIUUVV"},
}

// Empty CSW24 board. Player 0 is on turn with the rack we override.
const emptyBoardCGP = "15/15/15/15/15/15/15/15/15/15/15/15/15/15/15 AEINRST/AEIORST 0/0 0 lex CSW24;"

// Late-bag CSW24 position borrowed from explainer/tools_test.go. Bag
// has only a few tiles left and the board is dense with playthrough
// opportunities, exercising the WMP shadow / wmpLeaves branches.
const explainerEndCGP = "PEC4D3QUAY/1EUOI2UG4V1/2MINX1ER3TI1/5UNTANGLeD1/8I3N2/6RONZ2T2/5HOPE1T1H2/3COMBES1R4/2BOW5A4/3V1ASEItIES2/3EEW4T4/3DAD9/5L9/15/15 AFLOORY/AAFGNRT 337/281 0 lex CSW24;"

func runTopPlayEquivalence(t *testing.T, w *wmppkg.WMP, c equivalenceCase) {
	is := is.New(t)

	noGen, noGame := makeEquivGenerator(t, c.cgp, false)
	noRack := tilemapping.RackFromString(c.rack, noGame.Alphabet())
	noGen.GenAll(noRack, true) // addExchange = true so exchanges are considered
	noPlays := copyMoveSlice(noGen.Plays())
	is.True(len(noPlays) > 0)

	wmpGen, wmpGame := makeEquivGenerator(t, c.cgp, true)
	wmpGen.SetWMP(w)
	wmpRack := tilemapping.RackFromString(c.rack, wmpGame.Alphabet())
	wmpGen.GenAll(wmpRack, true)
	wmpPlays := copyMoveSlice(wmpGen.Plays())
	is.True(len(wmpPlays) > 0)

	noTop := noPlays[0]
	wmpTop := wmpPlays[0]

	if noTop.ShortDescription() != wmpTop.ShortDescription() {
		t.Errorf("top play mismatch:\n  noWMP: %s (score %d eq %.4f)\n  WMP:   %s (score %d eq %.4f)",
			noTop.ShortDescription(), noTop.Score(), noTop.Equity(),
			wmpTop.ShortDescription(), wmpTop.Score(), wmpTop.Equity())
	}
	if noTop.Score() != wmpTop.Score() {
		t.Errorf("top score mismatch: noWMP=%d WMP=%d", noTop.Score(), wmpTop.Score())
	}
	if absDiff(noTop.Equity(), wmpTop.Equity()) > 1e-6 {
		t.Errorf("top equity mismatch: noWMP=%.6f WMP=%.6f", noTop.Equity(), wmpTop.Equity())
	}
}

func runTopNAreLegal(t *testing.T, w *wmppkg.WMP, c equivalenceCase, n int) {
	is := is.New(t)

	// Run noWMP with AllPlaysRecorder so we have the COMPLETE play
	// set to validate against. AllPlaysRecorder doesn't use shadow,
	// so this is shadow-free reference data. We have to assign
	// equities post-hoc since AllPlaysRecorder only sets the score.
	noGen, noGame, noCalc := makeEquivGeneratorAll(t, c.cgp)
	noRack := tilemapping.RackFromString(c.rack, noGame.Alphabet())
	noGen.GenAll(noRack, true)
	noAll := noGen.Plays()
	is.True(len(noAll) > 0)
	bag := noGame.Game.Bag()
	oppRack := noGame.Game.RackFor(1 - noGame.Game.PlayerOnTurn())
	for _, m := range noAll {
		eq := noCalc.Equity(m, noGame.Game.Board(), bag, oppRack)
		m.SetEquity(eq)
	}
	noByDesc := make(map[string]*move.Move, len(noAll))
	for _, p := range noAll {
		noByDesc[p.ShortDescription()] = p
	}

	// Run WMP with TopNPlayRecorder.
	wmpGen, wmpGame := makeEquivGeneratorTopN(t, c.cgp, n, true)
	wmpGen.SetWMP(w)
	wmpRack := tilemapping.RackFromString(c.rack, wmpGame.Alphabet())
	wmpGen.GenAll(wmpRack, true)
	wmpPlays := copyMoveSlice(wmpGen.Plays())
	is.True(len(wmpPlays) > 0)

	// Every WMP play must be a real play in the noWMP full set, with
	// matching score + equity. WMP fabricating a play, scoring it
	// wrong, or putting it at the wrong coords would all surface here.
	// We skip Pass moves: GenAllWithShadow's Pass-fallback condition
	// (`len(gen.plays) == 0`) doesn't account for the TopNPlayRecorder
	// using topNPlays instead of plays, so Pass gets injected
	// unconditionally on the WMP side. AllPlaysRecorder doesn't add
	// Pass when other plays exist, so the comparison would fail. The
	// Pass behavior is the same with WMP off and is independent of
	// this PR.
	for _, wp := range wmpPlays {
		if wp.Action() == move.MoveTypePass {
			continue
		}
		desc := wp.ShortDescription()
		np, ok := noByDesc[desc]
		if !ok {
			t.Errorf("WMP returned play not in noWMP full set: %s score=%d eq=%.4f",
				desc, wp.Score(), wp.Equity())
			continue
		}
		if np.Score() != wp.Score() {
			t.Errorf("score mismatch for %s: noWMP=%d WMP=%d",
				desc, np.Score(), wp.Score())
		}
		if absDiff(np.Equity(), wp.Equity()) > 1e-6 {
			t.Errorf("equity mismatch for %s: noWMP=%.6f WMP=%.6f",
				desc, np.Equity(), wp.Equity())
		}
	}
}

// makeEquivGenerator builds a fresh GordonGenerator wired up for
// TopPlayOnlyRecorder. Each call gets its own ParsedCGP / equity
// calculator so leave map / shadow state never bleeds across runs.
func makeEquivGenerator(t *testing.T, cgpStr string, _ bool) (*movegen.GordonGenerator, *cgp.ParsedCGP) {
	t.Helper()
	is := is.New(t)

	game, err := cgp.ParseCGP(DefaultConfig, cgpStr)
	is.NoErr(err)
	game.RecalculateBoard()

	calc, err := equity.NewCombinedStaticCalculator(
		"CSW24", DefaultConfig, "", equity.PEGAdjustmentFilename)
	is.NoErr(err)

	gd, err := kwg.GetKWG(game.Config().WGLConfig(), game.LexiconName())
	is.NoErr(err)

	gen := movegen.NewGordonGenerator(gd, game.Board(), game.Rules().LetterDistribution())
	gen.SetEquityCalculators([]equity.EquityCalculator{calc})
	gen.SetGame(game.Game)
	gen.SetPlayRecorderTopPlay()
	return gen, game
}

// makeEquivGeneratorAll builds a fresh GordonGenerator with the
// default AllPlaysRecorder (no shadow), giving the complete play set.
// Returned alongside the game and the CombinedStaticCalculator the
// caller uses to assign equities post-hoc.
func makeEquivGeneratorAll(t *testing.T, cgpStr string) (*movegen.GordonGenerator, *cgp.ParsedCGP, *equity.CombinedStaticCalculator) {
	t.Helper()
	is := is.New(t)

	game, err := cgp.ParseCGP(DefaultConfig, cgpStr)
	is.NoErr(err)
	game.RecalculateBoard()

	calc, err := equity.NewCombinedStaticCalculator(
		"CSW24", DefaultConfig, "", equity.PEGAdjustmentFilename)
	is.NoErr(err)

	gd, err := kwg.GetKWG(game.Config().WGLConfig(), game.LexiconName())
	is.NoErr(err)

	gen := movegen.NewGordonGenerator(gd, game.Board(), game.Rules().LetterDistribution())
	gen.SetEquityCalculators([]equity.EquityCalculator{calc})
	gen.SetGame(game.Game)
	return gen, game, calc
}

// makeEquivGeneratorTopN is like makeEquivGenerator but uses
// SetRecordNTopPlays(n) so the test can compare the Top-N list.
func makeEquivGeneratorTopN(t *testing.T, cgpStr string, n int, _ bool) (*movegen.GordonGenerator, *cgp.ParsedCGP) {
	t.Helper()
	is := is.New(t)

	game, err := cgp.ParseCGP(DefaultConfig, cgpStr)
	is.NoErr(err)
	game.RecalculateBoard()

	calc, err := equity.NewCombinedStaticCalculator(
		"CSW24", DefaultConfig, "", equity.PEGAdjustmentFilename)
	is.NoErr(err)

	gd, err := kwg.GetKWG(game.Config().WGLConfig(), game.LexiconName())
	is.NoErr(err)

	gen := movegen.NewGordonGenerator(gd, game.Board(), game.Rules().LetterDistribution())
	gen.SetEquityCalculators([]equity.EquityCalculator{calc})
	gen.SetGame(game.Game)
	gen.SetRecordNTopPlays(n)
	return gen, game
}

// copyMoveSlice deep-copies the move pointers so a subsequent GenAll
// (which reuses the generator's underlying buffer) can't clobber the
// snapshot we want to compare against.
func copyMoveSlice(in []*move.Move) []*move.Move {
	out := make([]*move.Move, len(in))
	for i, m := range in {
		c := &move.Move{}
		c.CopyFrom(m)
		out[i] = c
	}
	return out
}

func absDiff(a, b float64) float64 {
	if a > b {
		return a - b
	}
	return b - a
}
