local set_res = macondo_set('lexicon NWL18')
print(set_res)
local load_res = macondo_load('xt 32680')
print(load_res)
local res = macondo_turn('21')
print(res)
local res = macondo_gen('1')
print(res)
