// Code generated by protoc-gen-go. DO NOT EDIT.
// source: rpc/autoplayer/autoplayer.proto

package autoplayer

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PlayRequest struct {
	NumGames             int32    `protobuf:"varint,1,opt,name=num_games,json=numGames,proto3" json:"num_games,omitempty"`
	NumCores             int32    `protobuf:"varint,2,opt,name=num_cores,json=numCores,proto3" json:"num_cores,omitempty"`
	Comp1Engine          int32    `protobuf:"varint,3,opt,name=comp1_engine,json=comp1Engine,proto3" json:"comp1_engine,omitempty"`
	Comp2Engine          int32    `protobuf:"varint,4,opt,name=comp2_engine,json=comp2Engine,proto3" json:"comp2_engine,omitempty"`
	OutputFile           string   `protobuf:"bytes,5,opt,name=output_file,json=outputFile,proto3" json:"output_file,omitempty"`
	LexiconName          string   `protobuf:"bytes,6,opt,name=lexicon_name,json=lexiconName,proto3" json:"lexicon_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PlayRequest) Reset()         { *m = PlayRequest{} }
func (m *PlayRequest) String() string { return proto.CompactTextString(m) }
func (*PlayRequest) ProtoMessage()    {}
func (*PlayRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f5a6fe4a1afb16d3, []int{0}
}

func (m *PlayRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlayRequest.Unmarshal(m, b)
}
func (m *PlayRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlayRequest.Marshal(b, m, deterministic)
}
func (m *PlayRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlayRequest.Merge(m, src)
}
func (m *PlayRequest) XXX_Size() int {
	return xxx_messageInfo_PlayRequest.Size(m)
}
func (m *PlayRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PlayRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PlayRequest proto.InternalMessageInfo

func (m *PlayRequest) GetNumGames() int32 {
	if m != nil {
		return m.NumGames
	}
	return 0
}

func (m *PlayRequest) GetNumCores() int32 {
	if m != nil {
		return m.NumCores
	}
	return 0
}

func (m *PlayRequest) GetComp1Engine() int32 {
	if m != nil {
		return m.Comp1Engine
	}
	return 0
}

func (m *PlayRequest) GetComp2Engine() int32 {
	if m != nil {
		return m.Comp2Engine
	}
	return 0
}

func (m *PlayRequest) GetOutputFile() string {
	if m != nil {
		return m.OutputFile
	}
	return ""
}

func (m *PlayRequest) GetLexiconName() string {
	if m != nil {
		return m.LexiconName
	}
	return ""
}

type PlayResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PlayResponse) Reset()         { *m = PlayResponse{} }
func (m *PlayResponse) String() string { return proto.CompactTextString(m) }
func (*PlayResponse) ProtoMessage()    {}
func (*PlayResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f5a6fe4a1afb16d3, []int{1}
}

func (m *PlayResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlayResponse.Unmarshal(m, b)
}
func (m *PlayResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlayResponse.Marshal(b, m, deterministic)
}
func (m *PlayResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlayResponse.Merge(m, src)
}
func (m *PlayResponse) XXX_Size() int {
	return xxx_messageInfo_PlayResponse.Size(m)
}
func (m *PlayResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PlayResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PlayResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*PlayRequest)(nil), "autoplayer.PlayRequest")
	proto.RegisterType((*PlayResponse)(nil), "autoplayer.PlayResponse")
}

func init() { proto.RegisterFile("rpc/autoplayer/autoplayer.proto", fileDescriptor_f5a6fe4a1afb16d3) }

var fileDescriptor_f5a6fe4a1afb16d3 = []byte{
	// 247 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x90, 0x4d, 0x4b, 0xc3, 0x40,
	0x10, 0x86, 0x89, 0xb6, 0xc5, 0x4e, 0x4a, 0x91, 0xbd, 0xb8, 0xe8, 0xa1, 0xb5, 0xa7, 0x9e, 0x2a,
	0xc6, 0x93, 0x47, 0x15, 0xed, 0x4d, 0x4a, 0x8e, 0x5e, 0xc2, 0x1a, 0xc6, 0xb2, 0xb0, 0xbb, 0xb3,
	0xee, 0x07, 0xd8, 0x9f, 0xe9, 0x3f, 0x92, 0x6c, 0x1a, 0x13, 0xf1, 0x36, 0xf3, 0xbc, 0x0f, 0x03,
	0xf3, 0xc2, 0xc2, 0xd9, 0xfa, 0x46, 0xc4, 0x40, 0x56, 0x89, 0x03, 0xba, 0xc1, 0xb8, 0xb1, 0x8e,
	0x02, 0x31, 0xe8, 0xc9, 0xea, 0x3b, 0x83, 0x7c, 0xa7, 0xc4, 0xa1, 0xc4, 0xcf, 0x88, 0x3e, 0xb0,
	0x2b, 0x98, 0x9a, 0xa8, 0xab, 0xbd, 0xd0, 0xe8, 0x79, 0xb6, 0xcc, 0xd6, 0xe3, 0xf2, 0xcc, 0x44,
	0xbd, 0x6d, 0xf6, 0x2e, 0xac, 0xc9, 0xa1, 0xe7, 0x27, 0xbf, 0xe1, 0x53, 0xb3, 0xb3, 0x6b, 0x98,
	0xd5, 0xa4, 0xed, 0x6d, 0x85, 0x66, 0x2f, 0x0d, 0xf2, 0xd3, 0x94, 0xe7, 0x89, 0x3d, 0x27, 0xd4,
	0x29, 0x45, 0xa7, 0x8c, 0x7a, 0xa5, 0x38, 0x2a, 0x0b, 0xc8, 0x29, 0x06, 0x1b, 0x43, 0xf5, 0x21,
	0x15, 0xf2, 0xf1, 0x32, 0x5b, 0x4f, 0x4b, 0x68, 0xd1, 0x8b, 0x54, 0xe9, 0x86, 0xc2, 0x2f, 0x59,
	0x93, 0xa9, 0x8c, 0xd0, 0xc8, 0x27, 0xc9, 0xc8, 0x8f, 0xec, 0x55, 0x68, 0x5c, 0xcd, 0x61, 0xd6,
	0xbe, 0xe4, 0x2d, 0x19, 0x8f, 0xc5, 0x16, 0xe0, 0x21, 0x06, 0xda, 0xa5, 0x8f, 0xd9, 0x3d, 0x8c,
	0x9a, 0x89, 0x5d, 0x6c, 0x06, 0xc5, 0x0c, 0x2a, 0xb8, 0xe4, 0xff, 0x83, 0xf6, 0xd0, 0xe3, 0xf9,
	0xdb, 0xfc, 0x6f, 0xb7, 0xef, 0x93, 0xd4, 0xe8, 0xdd, 0x4f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x76,
	0x6f, 0xf0, 0x79, 0x74, 0x01, 0x00, 0x00,
}
