// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/proto/macondosvc.proto

package macondosvc

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GameEvent_Type int32

const (
	GameEvent_TILE_PLACEMENT_MOVE  GameEvent_Type = 0
	GameEvent_PHONY_TILES_RETURNED GameEvent_Type = 1
	GameEvent_PASS                 GameEvent_Type = 2
	GameEvent_CHALLENGE_BONUS      GameEvent_Type = 3
	GameEvent_EXCHANGE             GameEvent_Type = 4
	GameEvent_END_RACK_PTS         GameEvent_Type = 5
	GameEvent_TIME_PENALTY         GameEvent_Type = 6
	// Only for international rules (or after 6 zeroes)
	GameEvent_END_RACK_PENALTY GameEvent_Type = 7
)

var GameEvent_Type_name = map[int32]string{
	0: "TILE_PLACEMENT_MOVE",
	1: "PHONY_TILES_RETURNED",
	2: "PASS",
	3: "CHALLENGE_BONUS",
	4: "EXCHANGE",
	5: "END_RACK_PTS",
	6: "TIME_PENALTY",
	7: "END_RACK_PENALTY",
}

var GameEvent_Type_value = map[string]int32{
	"TILE_PLACEMENT_MOVE":  0,
	"PHONY_TILES_RETURNED": 1,
	"PASS":                 2,
	"CHALLENGE_BONUS":      3,
	"EXCHANGE":             4,
	"END_RACK_PTS":         5,
	"TIME_PENALTY":         6,
	"END_RACK_PENALTY":     7,
}

func (x GameEvent_Type) String() string {
	return proto.EnumName(GameEvent_Type_name, int32(x))
}

func (GameEvent_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_c01a15f985aab88c, []int{1, 0}
}

type GameEvent_Direction int32

const (
	GameEvent_HORIZONTAL GameEvent_Direction = 0
	GameEvent_VERTICAL   GameEvent_Direction = 1
)

var GameEvent_Direction_name = map[int32]string{
	0: "HORIZONTAL",
	1: "VERTICAL",
}

var GameEvent_Direction_value = map[string]int32{
	"HORIZONTAL": 0,
	"VERTICAL":   1,
}

func (x GameEvent_Direction) String() string {
	return proto.EnumName(GameEvent_Direction_name, int32(x))
}

func (GameEvent_Direction) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_c01a15f985aab88c, []int{1, 1}
}

// GameHistory encodes a whole history of a game, and it should also encode
// the initial board and tile configuration, etc. It can be considered
// to be an instantiation of a GCG file.
type GameHistory struct {
	Turns       []*GameTurn   `protobuf:"bytes,1,rep,name=turns,proto3" json:"turns,omitempty"`
	Players     []*PlayerInfo `protobuf:"bytes,2,rep,name=players,proto3" json:"players,omitempty"`
	Version     int32         `protobuf:"varint,3,opt,name=version,proto3" json:"version,omitempty"`
	OriginalGcg string        `protobuf:"bytes,4,opt,name=original_gcg,json=originalGcg,proto3" json:"original_gcg,omitempty"`
	Lexicon     string        `protobuf:"bytes,5,opt,name=lexicon,proto3" json:"lexicon,omitempty"`
	IdAuth      string        `protobuf:"bytes,6,opt,name=id_auth,json=idAuth,proto3" json:"id_auth,omitempty"`
	Uid         string        `protobuf:"bytes,7,opt,name=uid,proto3" json:"uid,omitempty"`
	Title       string        `protobuf:"bytes,8,opt,name=title,proto3" json:"title,omitempty"`
	Description string        `protobuf:"bytes,9,opt,name=description,proto3" json:"description,omitempty"`
	// last_known_racks should only be set in an incomplete / in-progress game.
	// if set, player racks should be set to these values.
	LastKnownRacks       []string `protobuf:"bytes,10,rep,name=last_known_racks,json=lastKnownRacks,proto3" json:"last_known_racks,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GameHistory) Reset()         { *m = GameHistory{} }
func (m *GameHistory) String() string { return proto.CompactTextString(m) }
func (*GameHistory) ProtoMessage()    {}
func (*GameHistory) Descriptor() ([]byte, []int) {
	return fileDescriptor_c01a15f985aab88c, []int{0}
}

func (m *GameHistory) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GameHistory.Unmarshal(m, b)
}
func (m *GameHistory) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GameHistory.Marshal(b, m, deterministic)
}
func (m *GameHistory) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GameHistory.Merge(m, src)
}
func (m *GameHistory) XXX_Size() int {
	return xxx_messageInfo_GameHistory.Size(m)
}
func (m *GameHistory) XXX_DiscardUnknown() {
	xxx_messageInfo_GameHistory.DiscardUnknown(m)
}

var xxx_messageInfo_GameHistory proto.InternalMessageInfo

func (m *GameHistory) GetTurns() []*GameTurn {
	if m != nil {
		return m.Turns
	}
	return nil
}

func (m *GameHistory) GetPlayers() []*PlayerInfo {
	if m != nil {
		return m.Players
	}
	return nil
}

func (m *GameHistory) GetVersion() int32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *GameHistory) GetOriginalGcg() string {
	if m != nil {
		return m.OriginalGcg
	}
	return ""
}

func (m *GameHistory) GetLexicon() string {
	if m != nil {
		return m.Lexicon
	}
	return ""
}

func (m *GameHistory) GetIdAuth() string {
	if m != nil {
		return m.IdAuth
	}
	return ""
}

func (m *GameHistory) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *GameHistory) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *GameHistory) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *GameHistory) GetLastKnownRacks() []string {
	if m != nil {
		return m.LastKnownRacks
	}
	return nil
}

// This should be merged into Move.
type GameEvent struct {
	Nickname    string              `protobuf:"bytes,1,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Note        string              `protobuf:"bytes,2,opt,name=note,proto3" json:"note,omitempty"`
	Rack        string              `protobuf:"bytes,3,opt,name=rack,proto3" json:"rack,omitempty"`
	Type        GameEvent_Type      `protobuf:"varint,4,opt,name=type,proto3,enum=GameEvent_Type" json:"type,omitempty"`
	Cumulative  int32               `protobuf:"varint,5,opt,name=cumulative,proto3" json:"cumulative,omitempty"`
	Row         int32               `protobuf:"varint,6,opt,name=row,proto3" json:"row,omitempty"`
	Column      int32               `protobuf:"varint,7,opt,name=column,proto3" json:"column,omitempty"`
	Direction   GameEvent_Direction `protobuf:"varint,8,opt,name=direction,proto3,enum=GameEvent_Direction" json:"direction,omitempty"`
	Position    string              `protobuf:"bytes,9,opt,name=position,proto3" json:"position,omitempty"`
	PlayedTiles string              `protobuf:"bytes,10,opt,name=played_tiles,json=playedTiles,proto3" json:"played_tiles,omitempty"`
	// An event will not have all of these; it depends on the type of the event.
	Exchanged            string   `protobuf:"bytes,11,opt,name=exchanged,proto3" json:"exchanged,omitempty"`
	Score                int32    `protobuf:"varint,12,opt,name=score,proto3" json:"score,omitempty"`
	Bonus                int32    `protobuf:"varint,13,opt,name=bonus,proto3" json:"bonus,omitempty"`
	EndRackPoints        int32    `protobuf:"varint,14,opt,name=end_rack_points,json=endRackPoints,proto3" json:"end_rack_points,omitempty"`
	LostScore            int32    `protobuf:"varint,15,opt,name=lost_score,json=lostScore,proto3" json:"lost_score,omitempty"`
	IsBingo              bool     `protobuf:"varint,16,opt,name=is_bingo,json=isBingo,proto3" json:"is_bingo,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GameEvent) Reset()         { *m = GameEvent{} }
func (m *GameEvent) String() string { return proto.CompactTextString(m) }
func (*GameEvent) ProtoMessage()    {}
func (*GameEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_c01a15f985aab88c, []int{1}
}

func (m *GameEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GameEvent.Unmarshal(m, b)
}
func (m *GameEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GameEvent.Marshal(b, m, deterministic)
}
func (m *GameEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GameEvent.Merge(m, src)
}
func (m *GameEvent) XXX_Size() int {
	return xxx_messageInfo_GameEvent.Size(m)
}
func (m *GameEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_GameEvent.DiscardUnknown(m)
}

var xxx_messageInfo_GameEvent proto.InternalMessageInfo

func (m *GameEvent) GetNickname() string {
	if m != nil {
		return m.Nickname
	}
	return ""
}

func (m *GameEvent) GetNote() string {
	if m != nil {
		return m.Note
	}
	return ""
}

func (m *GameEvent) GetRack() string {
	if m != nil {
		return m.Rack
	}
	return ""
}

func (m *GameEvent) GetType() GameEvent_Type {
	if m != nil {
		return m.Type
	}
	return GameEvent_TILE_PLACEMENT_MOVE
}

func (m *GameEvent) GetCumulative() int32 {
	if m != nil {
		return m.Cumulative
	}
	return 0
}

func (m *GameEvent) GetRow() int32 {
	if m != nil {
		return m.Row
	}
	return 0
}

func (m *GameEvent) GetColumn() int32 {
	if m != nil {
		return m.Column
	}
	return 0
}

func (m *GameEvent) GetDirection() GameEvent_Direction {
	if m != nil {
		return m.Direction
	}
	return GameEvent_HORIZONTAL
}

func (m *GameEvent) GetPosition() string {
	if m != nil {
		return m.Position
	}
	return ""
}

func (m *GameEvent) GetPlayedTiles() string {
	if m != nil {
		return m.PlayedTiles
	}
	return ""
}

func (m *GameEvent) GetExchanged() string {
	if m != nil {
		return m.Exchanged
	}
	return ""
}

func (m *GameEvent) GetScore() int32 {
	if m != nil {
		return m.Score
	}
	return 0
}

func (m *GameEvent) GetBonus() int32 {
	if m != nil {
		return m.Bonus
	}
	return 0
}

func (m *GameEvent) GetEndRackPoints() int32 {
	if m != nil {
		return m.EndRackPoints
	}
	return 0
}

func (m *GameEvent) GetLostScore() int32 {
	if m != nil {
		return m.LostScore
	}
	return 0
}

func (m *GameEvent) GetIsBingo() bool {
	if m != nil {
		return m.IsBingo
	}
	return false
}

type GameTurn struct {
	Events               []*GameEvent `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *GameTurn) Reset()         { *m = GameTurn{} }
func (m *GameTurn) String() string { return proto.CompactTextString(m) }
func (*GameTurn) ProtoMessage()    {}
func (*GameTurn) Descriptor() ([]byte, []int) {
	return fileDescriptor_c01a15f985aab88c, []int{2}
}

func (m *GameTurn) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GameTurn.Unmarshal(m, b)
}
func (m *GameTurn) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GameTurn.Marshal(b, m, deterministic)
}
func (m *GameTurn) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GameTurn.Merge(m, src)
}
func (m *GameTurn) XXX_Size() int {
	return xxx_messageInfo_GameTurn.Size(m)
}
func (m *GameTurn) XXX_DiscardUnknown() {
	xxx_messageInfo_GameTurn.DiscardUnknown(m)
}

var xxx_messageInfo_GameTurn proto.InternalMessageInfo

func (m *GameTurn) GetEvents() []*GameEvent {
	if m != nil {
		return m.Events
	}
	return nil
}

type PlayerInfo struct {
	Nickname             string   `protobuf:"bytes,1,opt,name=nickname,proto3" json:"nickname,omitempty"`
	RealName             string   `protobuf:"bytes,2,opt,name=real_name,json=realName,proto3" json:"real_name,omitempty"`
	Number               int32    `protobuf:"varint,3,opt,name=number,proto3" json:"number,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PlayerInfo) Reset()         { *m = PlayerInfo{} }
func (m *PlayerInfo) String() string { return proto.CompactTextString(m) }
func (*PlayerInfo) ProtoMessage()    {}
func (*PlayerInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_c01a15f985aab88c, []int{3}
}

func (m *PlayerInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlayerInfo.Unmarshal(m, b)
}
func (m *PlayerInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlayerInfo.Marshal(b, m, deterministic)
}
func (m *PlayerInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlayerInfo.Merge(m, src)
}
func (m *PlayerInfo) XXX_Size() int {
	return xxx_messageInfo_PlayerInfo.Size(m)
}
func (m *PlayerInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_PlayerInfo.DiscardUnknown(m)
}

var xxx_messageInfo_PlayerInfo proto.InternalMessageInfo

func (m *PlayerInfo) GetNickname() string {
	if m != nil {
		return m.Nickname
	}
	return ""
}

func (m *PlayerInfo) GetRealName() string {
	if m != nil {
		return m.RealName
	}
	return ""
}

func (m *PlayerInfo) GetNumber() int32 {
	if m != nil {
		return m.Number
	}
	return 0
}

type SetRackRequest struct {
	GameUuid             string   `protobuf:"bytes,1,opt,name=game_uuid,json=gameUuid,proto3" json:"game_uuid,omitempty"`
	Turnnum              int32    `protobuf:"varint,2,opt,name=turnnum,proto3" json:"turnnum,omitempty"`
	RackLetters          string   `protobuf:"bytes,3,opt,name=rack_letters,json=rackLetters,proto3" json:"rack_letters,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetRackRequest) Reset()         { *m = SetRackRequest{} }
func (m *SetRackRequest) String() string { return proto.CompactTextString(m) }
func (*SetRackRequest) ProtoMessage()    {}
func (*SetRackRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c01a15f985aab88c, []int{4}
}

func (m *SetRackRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetRackRequest.Unmarshal(m, b)
}
func (m *SetRackRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetRackRequest.Marshal(b, m, deterministic)
}
func (m *SetRackRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetRackRequest.Merge(m, src)
}
func (m *SetRackRequest) XXX_Size() int {
	return xxx_messageInfo_SetRackRequest.Size(m)
}
func (m *SetRackRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetRackRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetRackRequest proto.InternalMessageInfo

func (m *SetRackRequest) GetGameUuid() string {
	if m != nil {
		return m.GameUuid
	}
	return ""
}

func (m *SetRackRequest) GetTurnnum() int32 {
	if m != nil {
		return m.Turnnum
	}
	return 0
}

func (m *SetRackRequest) GetRackLetters() string {
	if m != nil {
		return m.RackLetters
	}
	return ""
}

type NewGameRequest struct {
	Players              []*PlayerInfo `protobuf:"bytes,1,rep,name=players,proto3" json:"players,omitempty"`
	BoardLayout          []string      `protobuf:"bytes,2,rep,name=board_layout,json=boardLayout,proto3" json:"board_layout,omitempty"`
	Lexicon              string        `protobuf:"bytes,3,opt,name=lexicon,proto3" json:"lexicon,omitempty"`
	LetterDistribution   string        `protobuf:"bytes,4,opt,name=letter_distribution,json=letterDistribution,proto3" json:"letter_distribution,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *NewGameRequest) Reset()         { *m = NewGameRequest{} }
func (m *NewGameRequest) String() string { return proto.CompactTextString(m) }
func (*NewGameRequest) ProtoMessage()    {}
func (*NewGameRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c01a15f985aab88c, []int{5}
}

func (m *NewGameRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewGameRequest.Unmarshal(m, b)
}
func (m *NewGameRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewGameRequest.Marshal(b, m, deterministic)
}
func (m *NewGameRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewGameRequest.Merge(m, src)
}
func (m *NewGameRequest) XXX_Size() int {
	return xxx_messageInfo_NewGameRequest.Size(m)
}
func (m *NewGameRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_NewGameRequest.DiscardUnknown(m)
}

var xxx_messageInfo_NewGameRequest proto.InternalMessageInfo

func (m *NewGameRequest) GetPlayers() []*PlayerInfo {
	if m != nil {
		return m.Players
	}
	return nil
}

func (m *NewGameRequest) GetBoardLayout() []string {
	if m != nil {
		return m.BoardLayout
	}
	return nil
}

func (m *NewGameRequest) GetLexicon() string {
	if m != nil {
		return m.Lexicon
	}
	return ""
}

func (m *NewGameRequest) GetLetterDistribution() string {
	if m != nil {
		return m.LetterDistribution
	}
	return ""
}

type LoadGCGRequest struct {
	Gcg                  string   `protobuf:"bytes,1,opt,name=gcg,proto3" json:"gcg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoadGCGRequest) Reset()         { *m = LoadGCGRequest{} }
func (m *LoadGCGRequest) String() string { return proto.CompactTextString(m) }
func (*LoadGCGRequest) ProtoMessage()    {}
func (*LoadGCGRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c01a15f985aab88c, []int{6}
}

func (m *LoadGCGRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoadGCGRequest.Unmarshal(m, b)
}
func (m *LoadGCGRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoadGCGRequest.Marshal(b, m, deterministic)
}
func (m *LoadGCGRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoadGCGRequest.Merge(m, src)
}
func (m *LoadGCGRequest) XXX_Size() int {
	return xxx_messageInfo_LoadGCGRequest.Size(m)
}
func (m *LoadGCGRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoadGCGRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoadGCGRequest proto.InternalMessageInfo

func (m *LoadGCGRequest) GetGcg() string {
	if m != nil {
		return m.Gcg
	}
	return ""
}

type GenMovesRequest struct {
	GameUuid             string   `protobuf:"bytes,1,opt,name=game_uuid,json=gameUuid,proto3" json:"game_uuid,omitempty"`
	Turnnum              int32    `protobuf:"varint,2,opt,name=turnnum,proto3" json:"turnnum,omitempty"`
	NumMoves             int32    `protobuf:"varint,3,opt,name=num_moves,json=numMoves,proto3" json:"num_moves,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GenMovesRequest) Reset()         { *m = GenMovesRequest{} }
func (m *GenMovesRequest) String() string { return proto.CompactTextString(m) }
func (*GenMovesRequest) ProtoMessage()    {}
func (*GenMovesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c01a15f985aab88c, []int{7}
}

func (m *GenMovesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GenMovesRequest.Unmarshal(m, b)
}
func (m *GenMovesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GenMovesRequest.Marshal(b, m, deterministic)
}
func (m *GenMovesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenMovesRequest.Merge(m, src)
}
func (m *GenMovesRequest) XXX_Size() int {
	return xxx_messageInfo_GenMovesRequest.Size(m)
}
func (m *GenMovesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GenMovesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GenMovesRequest proto.InternalMessageInfo

func (m *GenMovesRequest) GetGameUuid() string {
	if m != nil {
		return m.GameUuid
	}
	return ""
}

func (m *GenMovesRequest) GetTurnnum() int32 {
	if m != nil {
		return m.Turnnum
	}
	return 0
}

func (m *GenMovesRequest) GetNumMoves() int32 {
	if m != nil {
		return m.NumMoves
	}
	return 0
}

type MoveList struct {
	Moves                []*GameEvent `protobuf:"bytes,1,rep,name=moves,proto3" json:"moves,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *MoveList) Reset()         { *m = MoveList{} }
func (m *MoveList) String() string { return proto.CompactTextString(m) }
func (*MoveList) ProtoMessage()    {}
func (*MoveList) Descriptor() ([]byte, []int) {
	return fileDescriptor_c01a15f985aab88c, []int{8}
}

func (m *MoveList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MoveList.Unmarshal(m, b)
}
func (m *MoveList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MoveList.Marshal(b, m, deterministic)
}
func (m *MoveList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MoveList.Merge(m, src)
}
func (m *MoveList) XXX_Size() int {
	return xxx_messageInfo_MoveList.Size(m)
}
func (m *MoveList) XXX_DiscardUnknown() {
	xxx_messageInfo_MoveList.DiscardUnknown(m)
}

var xxx_messageInfo_MoveList proto.InternalMessageInfo

func (m *MoveList) GetMoves() []*GameEvent {
	if m != nil {
		return m.Moves
	}
	return nil
}

type MoveStatistic struct {
	Mean                 float64  `protobuf:"fixed64,1,opt,name=mean,proto3" json:"mean,omitempty"`
	Stdev                float64  `protobuf:"fixed64,2,opt,name=stdev,proto3" json:"stdev,omitempty"`
	TotalSamples         float64  `protobuf:"fixed64,3,opt,name=total_samples,json=totalSamples,proto3" json:"total_samples,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MoveStatistic) Reset()         { *m = MoveStatistic{} }
func (m *MoveStatistic) String() string { return proto.CompactTextString(m) }
func (*MoveStatistic) ProtoMessage()    {}
func (*MoveStatistic) Descriptor() ([]byte, []int) {
	return fileDescriptor_c01a15f985aab88c, []int{9}
}

func (m *MoveStatistic) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MoveStatistic.Unmarshal(m, b)
}
func (m *MoveStatistic) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MoveStatistic.Marshal(b, m, deterministic)
}
func (m *MoveStatistic) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MoveStatistic.Merge(m, src)
}
func (m *MoveStatistic) XXX_Size() int {
	return xxx_messageInfo_MoveStatistic.Size(m)
}
func (m *MoveStatistic) XXX_DiscardUnknown() {
	xxx_messageInfo_MoveStatistic.DiscardUnknown(m)
}

var xxx_messageInfo_MoveStatistic proto.InternalMessageInfo

func (m *MoveStatistic) GetMean() float64 {
	if m != nil {
		return m.Mean
	}
	return 0
}

func (m *MoveStatistic) GetStdev() float64 {
	if m != nil {
		return m.Stdev
	}
	return 0
}

func (m *MoveStatistic) GetTotalSamples() float64 {
	if m != nil {
		return m.TotalSamples
	}
	return 0
}

type SimulatedMove struct {
	Move *GameEvent `protobuf:"bytes,1,opt,name=move,proto3" json:"move,omitempty"`
	// Per-ply statistics
	ScoreStats []*MoveStatistic `protobuf:"bytes,2,rep,name=score_stats,json=scoreStats,proto3" json:"score_stats,omitempty"`
	BingoStats []*MoveStatistic `protobuf:"bytes,3,rep,name=bingo_stats,json=bingoStats,proto3" json:"bingo_stats,omitempty"`
	// Per-simulation statistics
	// Equity =  spread_stats + leftover_stats + any board consideration?
	SpreadStats          *MoveStatistic `protobuf:"bytes,4,opt,name=spread_stats,json=spreadStats,proto3" json:"spread_stats,omitempty"`
	LeftoverStats        *MoveStatistic `protobuf:"bytes,5,opt,name=leftover_stats,json=leftoverStats,proto3" json:"leftover_stats,omitempty"`
	EquityStats          *MoveStatistic `protobuf:"bytes,6,opt,name=equity_stats,json=equityStats,proto3" json:"equity_stats,omitempty"`
	WinStats             *MoveStatistic `protobuf:"bytes,7,opt,name=win_stats,json=winStats,proto3" json:"win_stats,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *SimulatedMove) Reset()         { *m = SimulatedMove{} }
func (m *SimulatedMove) String() string { return proto.CompactTextString(m) }
func (*SimulatedMove) ProtoMessage()    {}
func (*SimulatedMove) Descriptor() ([]byte, []int) {
	return fileDescriptor_c01a15f985aab88c, []int{10}
}

func (m *SimulatedMove) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SimulatedMove.Unmarshal(m, b)
}
func (m *SimulatedMove) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SimulatedMove.Marshal(b, m, deterministic)
}
func (m *SimulatedMove) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SimulatedMove.Merge(m, src)
}
func (m *SimulatedMove) XXX_Size() int {
	return xxx_messageInfo_SimulatedMove.Size(m)
}
func (m *SimulatedMove) XXX_DiscardUnknown() {
	xxx_messageInfo_SimulatedMove.DiscardUnknown(m)
}

var xxx_messageInfo_SimulatedMove proto.InternalMessageInfo

func (m *SimulatedMove) GetMove() *GameEvent {
	if m != nil {
		return m.Move
	}
	return nil
}

func (m *SimulatedMove) GetScoreStats() []*MoveStatistic {
	if m != nil {
		return m.ScoreStats
	}
	return nil
}

func (m *SimulatedMove) GetBingoStats() []*MoveStatistic {
	if m != nil {
		return m.BingoStats
	}
	return nil
}

func (m *SimulatedMove) GetSpreadStats() *MoveStatistic {
	if m != nil {
		return m.SpreadStats
	}
	return nil
}

func (m *SimulatedMove) GetLeftoverStats() *MoveStatistic {
	if m != nil {
		return m.LeftoverStats
	}
	return nil
}

func (m *SimulatedMove) GetEquityStats() *MoveStatistic {
	if m != nil {
		return m.EquityStats
	}
	return nil
}

func (m *SimulatedMove) GetWinStats() *MoveStatistic {
	if m != nil {
		return m.WinStats
	}
	return nil
}

type SimulateMovesRequest struct {
	GameUuid             string       `protobuf:"bytes,1,opt,name=game_uuid,json=gameUuid,proto3" json:"game_uuid,omitempty"`
	Turnnum              int32        `protobuf:"varint,2,opt,name=turnnum,proto3" json:"turnnum,omitempty"`
	Moves                []*GameEvent `protobuf:"bytes,3,rep,name=moves,proto3" json:"moves,omitempty"`
	Cores                int32        `protobuf:"varint,4,opt,name=cores,proto3" json:"cores,omitempty"`
	Plies                int32        `protobuf:"varint,5,opt,name=plies,proto3" json:"plies,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *SimulateMovesRequest) Reset()         { *m = SimulateMovesRequest{} }
func (m *SimulateMovesRequest) String() string { return proto.CompactTextString(m) }
func (*SimulateMovesRequest) ProtoMessage()    {}
func (*SimulateMovesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c01a15f985aab88c, []int{11}
}

func (m *SimulateMovesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SimulateMovesRequest.Unmarshal(m, b)
}
func (m *SimulateMovesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SimulateMovesRequest.Marshal(b, m, deterministic)
}
func (m *SimulateMovesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SimulateMovesRequest.Merge(m, src)
}
func (m *SimulateMovesRequest) XXX_Size() int {
	return xxx_messageInfo_SimulateMovesRequest.Size(m)
}
func (m *SimulateMovesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SimulateMovesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SimulateMovesRequest proto.InternalMessageInfo

func (m *SimulateMovesRequest) GetGameUuid() string {
	if m != nil {
		return m.GameUuid
	}
	return ""
}

func (m *SimulateMovesRequest) GetTurnnum() int32 {
	if m != nil {
		return m.Turnnum
	}
	return 0
}

func (m *SimulateMovesRequest) GetMoves() []*GameEvent {
	if m != nil {
		return m.Moves
	}
	return nil
}

func (m *SimulateMovesRequest) GetCores() int32 {
	if m != nil {
		return m.Cores
	}
	return 0
}

func (m *SimulateMovesRequest) GetPlies() int32 {
	if m != nil {
		return m.Plies
	}
	return 0
}

// Only one simulation can be going on at any given time. This will probably
// still be the case if I expose that in a multiplayer server, although
// the way simulation will work there is likely to be in-browser (Emscripten
// style) or something similar. So there's no need to provide a simulation ID.
type StopSimulationRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StopSimulationRequest) Reset()         { *m = StopSimulationRequest{} }
func (m *StopSimulationRequest) String() string { return proto.CompactTextString(m) }
func (*StopSimulationRequest) ProtoMessage()    {}
func (*StopSimulationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c01a15f985aab88c, []int{12}
}

func (m *StopSimulationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StopSimulationRequest.Unmarshal(m, b)
}
func (m *StopSimulationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StopSimulationRequest.Marshal(b, m, deterministic)
}
func (m *StopSimulationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StopSimulationRequest.Merge(m, src)
}
func (m *StopSimulationRequest) XXX_Size() int {
	return xxx_messageInfo_StopSimulationRequest.Size(m)
}
func (m *StopSimulationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StopSimulationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StopSimulationRequest proto.InternalMessageInfo

type SimulateAcknowledgement struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SimulateAcknowledgement) Reset()         { *m = SimulateAcknowledgement{} }
func (m *SimulateAcknowledgement) String() string { return proto.CompactTextString(m) }
func (*SimulateAcknowledgement) ProtoMessage()    {}
func (*SimulateAcknowledgement) Descriptor() ([]byte, []int) {
	return fileDescriptor_c01a15f985aab88c, []int{13}
}

func (m *SimulateAcknowledgement) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SimulateAcknowledgement.Unmarshal(m, b)
}
func (m *SimulateAcknowledgement) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SimulateAcknowledgement.Marshal(b, m, deterministic)
}
func (m *SimulateAcknowledgement) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SimulateAcknowledgement.Merge(m, src)
}
func (m *SimulateAcknowledgement) XXX_Size() int {
	return xxx_messageInfo_SimulateAcknowledgement.Size(m)
}
func (m *SimulateAcknowledgement) XXX_DiscardUnknown() {
	xxx_messageInfo_SimulateAcknowledgement.DiscardUnknown(m)
}

var xxx_messageInfo_SimulateAcknowledgement proto.InternalMessageInfo

type GetSimStatsRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetSimStatsRequest) Reset()         { *m = GetSimStatsRequest{} }
func (m *GetSimStatsRequest) String() string { return proto.CompactTextString(m) }
func (*GetSimStatsRequest) ProtoMessage()    {}
func (*GetSimStatsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c01a15f985aab88c, []int{14}
}

func (m *GetSimStatsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetSimStatsRequest.Unmarshal(m, b)
}
func (m *GetSimStatsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetSimStatsRequest.Marshal(b, m, deterministic)
}
func (m *GetSimStatsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetSimStatsRequest.Merge(m, src)
}
func (m *GetSimStatsRequest) XXX_Size() int {
	return xxx_messageInfo_GetSimStatsRequest.Size(m)
}
func (m *GetSimStatsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetSimStatsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetSimStatsRequest proto.InternalMessageInfo

type SimStatsResponse struct {
	Moves                []*SimulatedMove `protobuf:"bytes,1,rep,name=moves,proto3" json:"moves,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *SimStatsResponse) Reset()         { *m = SimStatsResponse{} }
func (m *SimStatsResponse) String() string { return proto.CompactTextString(m) }
func (*SimStatsResponse) ProtoMessage()    {}
func (*SimStatsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c01a15f985aab88c, []int{15}
}

func (m *SimStatsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SimStatsResponse.Unmarshal(m, b)
}
func (m *SimStatsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SimStatsResponse.Marshal(b, m, deterministic)
}
func (m *SimStatsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SimStatsResponse.Merge(m, src)
}
func (m *SimStatsResponse) XXX_Size() int {
	return xxx_messageInfo_SimStatsResponse.Size(m)
}
func (m *SimStatsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SimStatsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SimStatsResponse proto.InternalMessageInfo

func (m *SimStatsResponse) GetMoves() []*SimulatedMove {
	if m != nil {
		return m.Moves
	}
	return nil
}

func init() {
	proto.RegisterEnum("GameEvent_Type", GameEvent_Type_name, GameEvent_Type_value)
	proto.RegisterEnum("GameEvent_Direction", GameEvent_Direction_name, GameEvent_Direction_value)
	proto.RegisterType((*GameHistory)(nil), "GameHistory")
	proto.RegisterType((*GameEvent)(nil), "GameEvent")
	proto.RegisterType((*GameTurn)(nil), "GameTurn")
	proto.RegisterType((*PlayerInfo)(nil), "PlayerInfo")
	proto.RegisterType((*SetRackRequest)(nil), "SetRackRequest")
	proto.RegisterType((*NewGameRequest)(nil), "NewGameRequest")
	proto.RegisterType((*LoadGCGRequest)(nil), "LoadGCGRequest")
	proto.RegisterType((*GenMovesRequest)(nil), "GenMovesRequest")
	proto.RegisterType((*MoveList)(nil), "MoveList")
	proto.RegisterType((*MoveStatistic)(nil), "MoveStatistic")
	proto.RegisterType((*SimulatedMove)(nil), "SimulatedMove")
	proto.RegisterType((*SimulateMovesRequest)(nil), "SimulateMovesRequest")
	proto.RegisterType((*StopSimulationRequest)(nil), "StopSimulationRequest")
	proto.RegisterType((*SimulateAcknowledgement)(nil), "SimulateAcknowledgement")
	proto.RegisterType((*GetSimStatsRequest)(nil), "GetSimStatsRequest")
	proto.RegisterType((*SimStatsResponse)(nil), "SimStatsResponse")
}

func init() { proto.RegisterFile("api/proto/macondosvc.proto", fileDescriptor_c01a15f985aab88c) }

var fileDescriptor_c01a15f985aab88c = []byte{
	// 1306 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x56, 0xdd, 0x6e, 0xdb, 0xc6,
	0x12, 0x0e, 0xad, 0x5f, 0x8e, 0x64, 0x89, 0x67, 0xed, 0xc4, 0x8c, 0x73, 0x4e, 0x8e, 0xc3, 0x9c,
	0x53, 0xa8, 0x68, 0x4b, 0xa3, 0x2e, 0x0a, 0x14, 0x68, 0x2f, 0xaa, 0xd8, 0x84, 0x6c, 0x44, 0x96,
	0x05, 0x4a, 0x09, 0x9a, 0x02, 0x2d, 0x41, 0x93, 0x1b, 0x65, 0x1b, 0x72, 0x57, 0xe1, 0x2e, 0xe5,
	0xf8, 0xb2, 0xcf, 0xd1, 0x9b, 0xde, 0xf4, 0xaa, 0x4f, 0xd0, 0x67, 0xe9, 0xcb, 0x14, 0xbb, 0x4b,
	0x5a, 0x52, 0xac, 0xe4, 0xa6, 0xbd, 0xdb, 0xf9, 0x66, 0x66, 0x67, 0xf8, 0xcd, 0xcf, 0x12, 0xf6,
	0xc3, 0x39, 0x39, 0x9c, 0x67, 0x4c, 0xb0, 0xc3, 0x34, 0x8c, 0x18, 0x8d, 0x19, 0x5f, 0x44, 0xae,
	0x02, 0x9c, 0x3f, 0xb6, 0xa0, 0x35, 0x08, 0x53, 0x7c, 0x4a, 0xb8, 0x60, 0xd9, 0x35, 0xfa, 0x2f,
	0xd4, 0x44, 0x9e, 0x51, 0x6e, 0x1b, 0x07, 0x95, 0x5e, 0xeb, 0xc8, 0x74, 0xa5, 0x72, 0x9a, 0x67,
	0xd4, 0xd7, 0x38, 0xfa, 0x3f, 0x34, 0xe6, 0x49, 0x78, 0x8d, 0x33, 0x6e, 0x6f, 0x29, 0x93, 0x96,
	0x3b, 0x56, 0xf2, 0x19, 0x7d, 0xc9, 0xfc, 0x52, 0x87, 0x6c, 0x68, 0x2c, 0x70, 0xc6, 0x09, 0xa3,
	0x76, 0xe5, 0xc0, 0xe8, 0xd5, 0xfc, 0x52, 0x44, 0x8f, 0xa0, 0xcd, 0x32, 0x32, 0x23, 0x34, 0x4c,
	0x82, 0x59, 0x34, 0xb3, 0xab, 0x07, 0x46, 0xcf, 0xf4, 0x5b, 0x25, 0x36, 0x88, 0x66, 0xd2, 0x39,
	0xc1, 0x6f, 0x49, 0xc4, 0xa8, 0x5d, 0x53, 0xda, 0x52, 0x44, 0x7b, 0xd0, 0x20, 0x71, 0x10, 0xe6,
	0xe2, 0x95, 0x5d, 0x57, 0x9a, 0x3a, 0x89, 0xfb, 0xb9, 0x78, 0x85, 0x2c, 0xa8, 0xe4, 0x24, 0xb6,
	0x1b, 0x0a, 0x94, 0x47, 0xb4, 0x0b, 0x35, 0x41, 0x44, 0x82, 0xed, 0xa6, 0xc2, 0xb4, 0x80, 0x0e,
	0xa0, 0x15, 0x63, 0x1e, 0x65, 0x64, 0x2e, 0x64, 0x6e, 0xa6, 0x0e, 0xbe, 0x02, 0xa1, 0x1e, 0x58,
	0x49, 0xc8, 0x45, 0xf0, 0x9a, 0xb2, 0x2b, 0x1a, 0x64, 0x61, 0xf4, 0x9a, 0xdb, 0x70, 0x50, 0xe9,
	0x99, 0x7e, 0x47, 0xe2, 0x4f, 0x25, 0xec, 0x4b, 0xd4, 0xf9, 0xbd, 0x06, 0xa6, 0xa4, 0xc7, 0x5b,
	0x60, 0x2a, 0xd0, 0x3e, 0x34, 0x29, 0x89, 0x5e, 0xd3, 0x30, 0xc5, 0xb6, 0xa1, 0xae, 0xbd, 0x91,
	0x11, 0x82, 0x2a, 0x65, 0x02, 0xdb, 0x5b, 0x0a, 0x57, 0x67, 0x89, 0xc9, 0xcb, 0x15, 0x3d, 0xa6,
	0xaf, 0xce, 0xe8, 0x31, 0x54, 0xc5, 0xf5, 0x1c, 0x2b, 0x4e, 0x3a, 0x47, 0x5d, 0xf7, 0xe6, 0x76,
	0x77, 0x7a, 0x3d, 0xc7, 0xbe, 0x52, 0xa2, 0x87, 0x00, 0x51, 0x9e, 0xe6, 0x49, 0x28, 0xc8, 0x02,
	0x2b, 0x82, 0x6a, 0xfe, 0x0a, 0x22, 0xa9, 0xc8, 0xd8, 0x95, 0xe2, 0xa7, 0xe6, 0xcb, 0x23, 0xba,
	0x07, 0xf5, 0x88, 0x25, 0x79, 0x4a, 0x15, 0x3f, 0x35, 0xbf, 0x90, 0xd0, 0x11, 0x98, 0x31, 0xc9,
	0x70, 0xa4, 0xa8, 0x68, 0xaa, 0x98, 0xbb, 0x2b, 0x31, 0x4f, 0x4a, 0x9d, 0xbf, 0x34, 0x93, 0x9f,
	0x39, 0x67, 0x9c, 0xac, 0xb0, 0x77, 0x23, 0xcb, 0xd2, 0xaa, 0xfa, 0xc7, 0x81, 0x20, 0x09, 0x96,
	0xb4, 0x29, 0x76, 0x35, 0x36, 0x95, 0x10, 0xfa, 0x37, 0x98, 0xf8, 0x6d, 0xf4, 0x2a, 0xa4, 0x33,
	0x1c, 0xdb, 0x2d, 0xa5, 0x5f, 0x02, 0xb2, 0x66, 0x3c, 0x62, 0x19, 0xb6, 0xdb, 0x2a, 0x4f, 0x2d,
	0x48, 0xf4, 0x92, 0xd1, 0x9c, 0xdb, 0xdb, 0x1a, 0x55, 0x02, 0xfa, 0x08, 0xba, 0x98, 0xc6, 0xaa,
	0x40, 0xc1, 0x9c, 0x11, 0x2a, 0xb8, 0xdd, 0x51, 0xfa, 0x6d, 0x4c, 0x63, 0x59, 0xa0, 0xb1, 0x02,
	0xd1, 0x7f, 0x00, 0x12, 0xc6, 0x45, 0xa0, 0x2f, 0xee, 0x2a, 0x13, 0x53, 0x22, 0x13, 0x75, 0xf9,
	0x7d, 0x68, 0x12, 0x1e, 0x5c, 0x12, 0x3a, 0x63, 0xb6, 0x75, 0x60, 0xf4, 0x9a, 0x7e, 0x83, 0xf0,
	0x27, 0x52, 0x74, 0x7e, 0x35, 0xa0, 0x2a, 0x79, 0x47, 0x7b, 0xb0, 0x33, 0x3d, 0x1b, 0x7a, 0xc1,
	0x78, 0xd8, 0x3f, 0xf6, 0xce, 0xbd, 0xd1, 0x34, 0x38, 0xbf, 0x78, 0xee, 0x59, 0x77, 0x90, 0x0d,
	0xbb, 0xe3, 0xd3, 0x8b, 0xd1, 0x8b, 0x40, 0xaa, 0x27, 0x81, 0xef, 0x4d, 0x9f, 0xf9, 0x23, 0xef,
	0xc4, 0x32, 0x50, 0x13, 0xaa, 0xe3, 0xfe, 0x64, 0x62, 0x6d, 0xa1, 0x1d, 0xe8, 0x1e, 0x9f, 0xf6,
	0x87, 0x43, 0x6f, 0x34, 0xf0, 0x82, 0x27, 0x17, 0xa3, 0x67, 0x13, 0xab, 0x82, 0xda, 0xd0, 0xf4,
	0xbe, 0x3b, 0x3e, 0xed, 0x8f, 0x06, 0x9e, 0x55, 0x45, 0x16, 0xb4, 0xbd, 0xd1, 0x49, 0xe0, 0xf7,
	0x8f, 0x9f, 0x06, 0xe3, 0xe9, 0xc4, 0xaa, 0x49, 0x64, 0x7a, 0x76, 0xee, 0x05, 0x63, 0x6f, 0xd4,
	0x1f, 0x4e, 0x5f, 0x58, 0x75, 0xb4, 0x0b, 0xd6, 0xd2, 0xa6, 0x40, 0x1b, 0xce, 0xc7, 0x60, 0xde,
	0x54, 0x09, 0x75, 0x00, 0x4e, 0x2f, 0xfc, 0xb3, 0xef, 0x2f, 0x46, 0xd3, 0xfe, 0xd0, 0xba, 0x23,
	0x83, 0x3c, 0xf7, 0xfc, 0xe9, 0xd9, 0x71, 0x7f, 0x68, 0x19, 0x8e, 0x0b, 0xcd, 0x72, 0x96, 0x91,
	0x03, 0x75, 0x2c, 0x4b, 0x5c, 0x8e, 0x39, 0x2c, 0xab, 0xee, 0x17, 0x1a, 0xe7, 0x07, 0x80, 0xe5,
	0x60, 0x7f, 0xb0, 0xbb, 0x1f, 0x80, 0x99, 0xe1, 0x30, 0x09, 0x94, 0x52, 0xb7, 0x78, 0x53, 0x02,
	0x23, 0xa9, 0xbc, 0x07, 0x75, 0x9a, 0xa7, 0x97, 0x38, 0x2b, 0xf6, 0x40, 0x21, 0x39, 0x3f, 0x41,
	0x67, 0x82, 0x85, 0xac, 0x93, 0x8f, 0xdf, 0xe4, 0x98, 0x0b, 0x79, 0xcd, 0x2c, 0x4c, 0x71, 0x90,
	0xcb, 0x41, 0x2e, 0x62, 0x48, 0xe0, 0x99, 0x9c, 0x66, 0x1b, 0x1a, 0x72, 0xff, 0xd0, 0x3c, 0x55,
	0x11, 0x6a, 0x7e, 0x29, 0xca, 0xa6, 0x53, 0x3d, 0x90, 0x60, 0x21, 0xe4, 0x56, 0xd2, 0xf3, 0xd4,
	0x92, 0xd8, 0x50, 0x43, 0xce, 0x6f, 0x06, 0x74, 0x46, 0xf8, 0x4a, 0x7e, 0x63, 0x19, 0x6c, 0x65,
	0x8d, 0x19, 0x1f, 0x58, 0x63, 0x8f, 0xa0, 0x7d, 0xc9, 0xc2, 0x2c, 0x0e, 0x92, 0xf0, 0x9a, 0xe5,
	0x42, 0xad, 0x3c, 0xd3, 0x6f, 0x29, 0x6c, 0xa8, 0xa0, 0xd5, 0x65, 0x55, 0x59, 0x5f, 0x56, 0x87,
	0xb0, 0xa3, 0x93, 0x0a, 0x62, 0xc2, 0x45, 0x46, 0x2e, 0x73, 0x35, 0x35, 0x7a, 0xe1, 0x21, 0xad,
	0x3a, 0x59, 0xd1, 0x38, 0x0e, 0x74, 0x86, 0x2c, 0x8c, 0x07, 0xc7, 0x83, 0x32, 0x4d, 0x0b, 0x2a,
	0x72, 0x47, 0x6a, 0x36, 0xe4, 0xd1, 0xc1, 0xd0, 0x1d, 0x60, 0x7a, 0xce, 0x16, 0x98, 0xff, 0x4d,
	0xe2, 0x1e, 0x80, 0x49, 0xf3, 0x34, 0x48, 0xe5, 0x55, 0x45, 0x71, 0x9a, 0x34, 0x4f, 0xd5, 0xd5,
	0xce, 0xa7, 0xd0, 0x94, 0x87, 0x21, 0xe1, 0x02, 0x1d, 0x40, 0x4d, 0x1b, 0xdd, 0x6e, 0x16, 0xad,
	0x70, 0x7e, 0x84, 0x6d, 0x69, 0x3d, 0x11, 0xa1, 0x20, 0x5c, 0x90, 0x48, 0x2e, 0xb7, 0x14, 0x87,
	0x54, 0x65, 0x63, 0xf8, 0xea, 0xac, 0x86, 0x5b, 0xc4, 0x78, 0xa1, 0xf2, 0x30, 0x7c, 0x2d, 0xa0,
	0xc7, 0xb0, 0x2d, 0x98, 0x08, 0x93, 0x80, 0x87, 0xe9, 0x3c, 0x29, 0x32, 0x31, 0xfc, 0xb6, 0x02,
	0x27, 0x1a, 0x73, 0xfe, 0xdc, 0x82, 0xed, 0x09, 0x51, 0x1b, 0x0e, 0xc7, 0x32, 0x12, 0x7a, 0x08,
	0x55, 0x19, 0x5a, 0x05, 0x58, 0x4f, 0x49, 0xe1, 0xe8, 0x10, 0x5a, 0x6a, 0xe0, 0x03, 0x2e, 0x42,
	0x51, 0x3e, 0x55, 0x1d, 0x77, 0x2d, 0x4b, 0x1f, 0x94, 0x89, 0x94, 0xb9, 0x74, 0x50, 0x4b, 0xa0,
	0x70, 0xa8, 0x6c, 0x76, 0x50, 0x26, 0xda, 0xe1, 0x73, 0x68, 0xf3, 0x79, 0x86, 0xc3, 0xb8, 0xf0,
	0xa8, 0xaa, 0x4c, 0xde, 0xf5, 0x68, 0x69, 0x1b, 0xed, 0xf2, 0x25, 0x74, 0x12, 0xfc, 0x52, 0xb0,
	0x05, 0xce, 0x0a, 0xa7, 0xda, 0x46, 0xa7, 0xed, 0xd2, 0xea, 0x26, 0x12, 0x7e, 0x93, 0x13, 0x71,
	0x5d, 0x38, 0xd5, 0x37, 0x47, 0xd2, 0x36, 0xda, 0xe5, 0x13, 0x30, 0xaf, 0x08, 0x2d, 0xec, 0x1b,
	0x1b, 0xed, 0x9b, 0x57, 0x84, 0x2a, 0x63, 0xe7, 0x17, 0x03, 0x76, 0x4b, 0x76, 0xff, 0x89, 0xc6,
	0xba, 0xe9, 0x97, 0xca, 0x7b, 0xfa, 0x45, 0xb6, 0x82, 0x64, 0x5e, 0x93, 0x56, 0xf3, 0xb5, 0x20,
	0xd1, 0x79, 0x42, 0x30, 0x2f, 0xde, 0x34, 0x2d, 0x38, 0x7b, 0x70, 0x77, 0x22, 0xd8, 0xbc, 0x48,
	0x50, 0xbe, 0x46, 0x3a, 0x3b, 0xe7, 0x3e, 0xec, 0x95, 0x59, 0xf7, 0x23, 0xf9, 0x5a, 0x27, 0x38,
	0x9e, 0xe1, 0x14, 0x53, 0xe1, 0xec, 0x02, 0x1a, 0x60, 0x31, 0x21, 0xa9, 0xfa, 0xc0, 0xd2, 0xe1,
	0x2b, 0xb0, 0x96, 0x10, 0x9f, 0x33, 0xca, 0x31, 0xfa, 0xdf, 0x7a, 0x6f, 0x77, 0xdc, 0xb5, 0x36,
	0x2b, 0xf2, 0x3d, 0xfa, 0xb9, 0x02, 0x77, 0xe5, 0x47, 0xf4, 0x29, 0x65, 0x42, 0x25, 0x31, 0xc1,
	0xd9, 0x82, 0x44, 0x18, 0xf5, 0xa0, 0x51, 0x6c, 0x16, 0xd4, 0x75, 0xd7, 0x77, 0xcc, 0x7e, 0xdb,
	0x5d, 0xfd, 0xb3, 0xea, 0x41, 0xa3, 0x18, 0x6e, 0xd4, 0x75, 0xd7, 0xc7, 0xfc, 0xb6, 0x65, 0xb1,
	0x1a, 0x51, 0xd7, 0x5d, 0x5f, 0x92, 0xef, 0x58, 0x7e, 0x06, 0xdb, 0x03, 0x4c, 0x71, 0x56, 0x16,
	0x0e, 0x59, 0xee, 0x3b, 0xcb, 0x61, 0x7f, 0x85, 0x7d, 0xf4, 0xed, 0x72, 0x8a, 0xb4, 0xf9, 0x5d,
	0x77, 0x53, 0xdd, 0xf7, 0x6d, 0xf7, 0x3d, 0xc4, 0xa2, 0xaf, 0xa1, 0xb3, 0x5e, 0x0c, 0x74, 0xcf,
	0xdd, 0x58, 0x9d, 0xfd, 0x7f, 0xb9, 0xb7, 0xb8, 0xfe, 0xa6, 0xac, 0x4a, 0x61, 0xaa, 0x5b, 0x75,
	0xc7, 0xbd, 0x5d, 0xaa, 0x0d, 0xde, 0x97, 0x75, 0xf5, 0xc3, 0xfa, 0xc5, 0x5f, 0x01, 0x00, 0x00,
	0xff, 0xff, 0xd5, 0x38, 0x32, 0x73, 0xce, 0x0a, 0x00, 0x00,
}
